# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'spanjaan.sitesearch::lang.models.querylog.label'

# Model Form Field configuration
form: $/spanjaan/sitesearch/models/querylog/fields.yaml

# Model Class name
modelClass: SpAnjaan\Sitesearch\Models\QueryLog

# Default redirect location
defaultRedirect: spanjaan/sitesearch/querylogs

# Create page
create:
    title: backend::lang.form.create_title
    redirect: spanjaan/sitesearch/querylogs/update/:id
    redirectClose: spanjaan/sitesearch/querylogs

# Update page
update:
    title: backend::lang.form.update_title
    redirect: spanjaan/sitesearch/querylogs
    redirectClose: spanjaan/sitesearch/querylogs

# Preview page
preview:
    title: backend::lang.form.preview_title
